# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for agendaDeEventos

target 'Woop Eventos' do
    pod 'Alamofire', '~> 4.7'
    pod 'Alamofire-SwiftyJSON'
    pod 'Kingfisher', '~> 4.0'
end
